### ISSUE TITLE
这个应用能让qq与tg消息互转吗？

### ISSUE THREAD

**Issue by Feiyuyu0503** [qwe7002/telegram-sms#2]
作者你好，偶然看到这个项目，很喜欢，也使用过了。想请教下可否做到让qq与tg消息间互转（我查到过efb-qq-slave,qq2tg这两个项目可以做到，但都需要用到coolq，部署起来比较麻烦）开发不易，如有冒犯，请谅解啦！

**Comment by qwe7002** [comment]
这个功能是没有的，这个bot只处理手机短信，来电等的信息。你的需求实话说现在除了coolq也没啥更好的转发方案了。
