### ISSUE TITLE
修改服务器地址

### ISSUE THREAD

**Issue by tinydream96** [qwe7002/telegram-sms#8]
能否将API.telegram.org这个服务器地址设置成可以在客户端修改？实际上用自己或者别人做的反代后可以避免某些问题。

**Comment by qwe7002** [comment]
这个出于安全考虑不打算设计成可以在客户端修改，如果有需要的话，请自己编译一份。

**Comment by qwe7002** [comment]
其实还有个方法，是用SNI代理，这个只需要建立好代理，然后修改本机的Host（记得把DNS over HTTPS关掉）就可以了。相比起您说的这种代理方法会安全的很多。毕竟没有经过ssl解密的过程。

**Comment by Neo-Zhixing** [comment]
> 这个出于安全考虑不打算设计成可以在客户端修改，如果有需要的话，请自己编译一份。你可以在`public_func`中找到`get_url`函数，这个函数是全局的URL获取函数。

使用了您的软件觉得非常好用，但如果支持设置api服务器地址，确实能够大大方便大家的使用。关于安全的问题，如果用户能保证api服务器的可信度，比如这个api服务器relay就是我自己建立的，那么我不认为支持客户端修改api地址会造成任何额外的安全问题。

没错，重新编译一份的确能解决这个问题，但是这个软件的用户并不都是做安卓开发的，如果重新安装开发环境确实是挺麻烦的。SNI代理也存在局限性，他要求我们拥有一个IP，不干别的，专门做SNI转发。总而言之，本来更改一个URL就能解决的事，没必要这么麻烦。

如果作者仍然存在安全顾虑，可以为这个选项添加警告，要求用户确保该api server的可信度。

**Comment by qwe7002** [comment]
> > 这个出于安全考虑不打算设计成可以在客户端修改，如果有需要的话，请自己编译一份。你可以在`public_func`中找到`get_url`函数，这个函数是全局的URL获取函数。
> 
> 使用了您的软件觉得非常好用，但如果支持设置api服务器地址，确实能够大大方便大家的使用。关于安全的问题，如果用户能保证api服务器的可信度，比如这个api服务器relay就是我自己建立的，那么我不认为支持客户端修改api地址会造成任何额外的安全问题。
> 
> 没错，重新编译一份的确能解决这个问题，但是这个软件的用户并不都是做安卓开发的，如果重新安装开发环境确实是挺麻烦的。SNI代理也存在局限性，他要求我们拥有一个IP，不干别的，专门做SNI转发。总而言之，本来更改一个URL就能解决的事，没必要这么麻烦。
> 
> 如果作者仍然存在安全顾虑，可以为这个选项添加警告，要求用户确保该api server的可信度。

但是非常抱歉，我认为用户没有能力可以确保这个api server是可信的。我必须要为这个软件的可靠性负责。sni代理其实不是必须要拥有一个ip不做别的专门用于转发，你可以使用Nginx的steam功能，在转发api.telegram.org的同时，转发你的网站（相当于是用steam去监听443端口，然后把https的站点开在另外一个端口上，让nginx的steam根据$ssl_preread_server_name提供的域名来判断是转发api.telegram.org还是转发你自己的网站）这个功能我这个版本绝对不会加入，所以只能说很抱歉。

**Comment by qwe7002** [comment]
> > 这个出于安全考虑不打算设计成可以在客户端修改，如果有需要的话，请自己编译一份。你可以在`public_func`中找到`get_url`函数，这个函数是全局的URL获取函数。
> 
> 使用了您的软件觉得非常好用，但如果支持设置api服务器地址，确实能够大大方便大家的使用。关于安全的问题，如果用户能保证api服务器的可信度，比如这个api服务器relay就是我自己建立的，那么我不认为支持客户端修改api地址会造成任何额外的安全问题。
> 
> 没错，重新编译一份的确能解决这个问题，但是这个软件的用户并不都是做安卓开发的，如果重新安装开发环境确实是挺麻烦的。SNI代理也存在局限性，他要求我们拥有一个IP，不干别的，专门做SNI转发。总而言之，本来更改一个URL就能解决的事，没必要这么麻烦。
> 
> 如果作者仍然存在安全顾虑，可以为这个选项添加警告，要求用户确保该api server的可信度。

还有一个非常非常折中的方法，我提供一个利用CI编译的脚本，让需要修改代码的用户，直接fork一份代码，然后直接修改代码，自动编译出apk。

**Comment by qwe7002** [comment]
> > 这个出于安全考虑不打算设计成可以在客户端修改，如果有需要的话，请自己编译一份。你可以在`public_func`中找到`get_url`函数，这个函数是全局的URL获取函数。
> 
> 使用了您的软件觉得非常好用，但如果支持设置api服务器地址，确实能够大大方便大家的使用。关于安全的问题，如果用户能保证api服务器的可信度，比如这个api服务器relay就是我自己建立的，那么我不认为支持客户端修改api地址会造成任何额外的安全问题。
> 
> 没错，重新编译一份的确能解决这个问题，但是这个软件的用户并不都是做安卓开发的，如果重新安装开发环境确实是挺麻烦的。SNI代理也存在局限性，他要求我们拥有一个IP，不干别的，专门做SNI转发。总而言之，本来更改一个URL就能解决的事，没必要这么麻烦。
> 
> 如果作者仍然存在安全顾虑，可以为这个选项添加警告，要求用户确保该api server的可信度。

我刚刚做了测试，可以在不安装任何编译环境的情况下，使用Github提供的Action编译出apk来。https://github.com/qwe7002/telegram-sms/actions 这个是编译的结果，https://github.com/qwe7002/telegram-sms/blob/master/.github/workflows/android.yml 编译脚本在这里，在我整理好之后，会把这个作为一个Example放进wiki中

**Comment by Neo-Zhixing** [comment]
> > > 这个出于安全考虑不打算设计成可以在客户端修改，如果有需要的话，请自己编译一份。你可以在`public_func`中找到`get_url`函数，这个函数是全局的URL获取函数。
> > 
> > 
> > 使用了您的软件觉得非常好用，但如果支持设置api服务器地址，确实能够大大方便大家的使用。关于安全的问题，如果用户能保证api服务器的可信度，比如这个api服务器relay就是我自己建立的，那么我不认为支持客户端修改api地址会造成任何额外的安全问题。
> > 没错，重新编译一份的确能解决这个问题，但是这个软件的用户并不都是做安卓开发的，如果重新安装开发环境确实是挺麻烦的。SNI代理也存在局限性，他要求我们拥有一个IP，不干别的，专门做SNI转发。总而言之，本来更改一个URL就能解决的事，没必要这么麻烦。
> > 如果作者仍然存在安全顾虑，可以为这个选项添加警告，要求用户确保该api server的可信度。
> 
> 我刚刚做了测试，可以在不安装任何编译环境的情况下，使用Github提供的Action编译出apk来。
> 
> https://github.com/qwe7002/telegram-sms/actions 这个是编译的结果，
> 
> https://github.com/qwe7002/telegram-sms/blob/master/.github/workflows/android.yml
> 
> 编译脚本在这里，在我整理好之后，会把这个作为一个Example放进wiki中

这的确是一个非常好的折中方法。我明白您的良苦用心，因为您可能是希望提高这个门槛，否则一定会出现tutorials，让用户在这个field输入一个特定的地址，然后黑客在这个地址拦截并查看用户短信的内容。您确实挺不容易的，在方便和安全之前平衡。

**Comment by Neo-Zhixing** [comment]
另外有一个可能的风险想提醒作者留意一下：万一有人更改服务器地址之后，distribute一个坏的apk呢？目前在app当中没有地方可以容易的看见这个api服务器地址到底是什么，因此我认为这个风险还是挺大的。

**Comment by qwe7002** [comment]
是这样的，感谢您的理解

Sent from my iPhone

On Dec 28, 2019, at 16:58, Zhixing Zhang <notifications@github.com> wrote:

﻿

这个出于安全考虑不打算设计成可以在客户端修改，如果有需要的话，请自己编译一份。你可以在public_func中找到get_url函数，这个函数是全局的URL获取函数。

使用了您的软件觉得非常好用，但如果支持设置api服务器地址，确实能够大大方便大家的使用。关于安全的问题，如果用户能保证api服务器的可信度，比如这个api服务器relay就是我自己建立的，那么我不认为支持客户端修改api地址会造成任何额外的安全问题。
没错，重新编译一份的确能解决这个问题，但是这个软件的用户并不都是做安卓开发的，如果重新安装开发环境确实是挺麻烦的。SNI代理也存在局限性，他要求我们拥有一个IP，不干别的，专门做SNI转发。总而言之，本来更改一个URL就能解决的事，没必要这么麻烦。
如果作者仍然存在安全顾虑，可以为这个选项添加警告，要求用户确保该api server的可信度。

我刚刚做了测试，可以在不安装任何编译环境的情况下，使用Github提供的Action编译出apk来。

https://github.com/qwe7002/telegram-sms/actions 这个是编译的结果，

https://github.com/qwe7002/telegram-sms/blob/master/.github/workflows/android.yml

编译脚本在这里，在我整理好之后，会把这个作为一个Example放进wiki中

这的确是一个非常好的折中方法。我明白您的良苦用心，因为您可能是希望提高这个门槛，否则一定会出现tutorials，让用户在这个field输入一个特定的地址，然后黑客在这个地址拦截并查看用户短信的内容。您确实挺不容易的，在方便和安全之前平衡。

**Comment by qwe7002** [comment]
这个问题我认为目前无解，原因在于，如果真的是有心人做了这么个修改，那他也不会忘记修改掉这个提示，让他显示出和实际不同的地址。我觉得比较好的方法还是呼吁各位在官方渠道下载软件，以及保护好软件的签名。

Sent from my iPhone

On Dec 28, 2019, at 17:01, Zhixing Zhang <notifications@github.com> wrote:

﻿

另外有一个可能的风险想提醒作者留意一下：万一有人更改服务器地址之后，distribute一个坏的apk呢？目前在app当中没有地方可以容易的看见这个api服务器地址到底是什么，因此我认为这个风险还是挺大的。
